% This script creates a series of images for the validation step of the image processing part of the variability of cell migration study.
% It uses the dat_temp.csv generated by the process_images.R script to generate the images with the cell trajectories and an overall
% image with all the cells.


%% Clear
clear all;
cd('D:/Data/MULTIMOT/Processed/XSP/JianJiang_experiment1/3 - Postprocessing results/')


%% Load experiment information, generated using R. I use xlsread because I can't import R list
[ndata, Files.root]  = xlsread('Files.xlsx',1);
[ndata, Files.paths]  = xlsread('Files.xlsx',2);
[ndata, description]  = xlsread('Files.xlsx',3);
Files.number_of_images_each = ndata(1);
Files.number_of_images_total = ndata(2);
[ndata, Files.Original_files]  = xlsread('Files.xlsx',4);
Settings.PixelNumber = 200;
Settings.PixelNumber_percell = 80;


%% Plot and save
set(0,'DefaultFigureWindowStyle','normal')

merge_images(Files, Settings)

plot_all(Files, Settings)
process_cells_individually(Files, Settings)
